version: '3.1'
services:

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
      MYSQL_USER: siva
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"

  postgres:
    image: postgres:10.7
    container_name: postgres-db
    environment:
      - POSTGRES_USER=siva
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
    restart: unless-stopped